# Generated by Django 5.1.6 on 2025-02-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pizza_topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='PizzaCheese',
            new_name='pizza_cheese',
        ),
        migrations.RenameModel(
            old_name='PizzaCrust',
            new_name='pizza_crust',
        ),
        migrations.RenameModel(
            old_name='PizzaSauce',
            new_name='pizza_sauce',
        ),
        migrations.RenameModel(
            old_name='PizzaSizes',
            new_name='pizza_size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='main.pizza_topping'),
        ),
    ]
