# Generated by Django 5.1.6 on 2025-02-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pizza_topping_rename_pizzacheese_pizza_cheese_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pizza_cheese',
            new_name='PizzaCheese',
        ),
        migrations.RenameModel(
            old_name='pizza_crust',
            new_name='PizzaCrust',
        ),
        migrations.RenameModel(
            old_name='pizza_sauce',
            new_name='PizzaSauce',
        ),
        migrations.RenameModel(
            old_name='pizza_size',
            new_name='PizzaSize',
        ),
        migrations.RenameModel(
            old_name='pizza_topping',
            new_name='PizzaTopping',
        ),
    ]
