# Generated by Django 5.1.6 on 2025-02-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_pizza_cheese_pizzacheese_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(choices=[('mozarella', 'mozarella'), ('vegan', 'vegan'), ('low fat', 'low fat')], default='mozzarella', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('thick', 'thick')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('large', 'large')], default='medium', max_length=20),
        ),
    ]
