# Generated by Django 5.1.6 on 2025-02-13 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pizza_cheese_alter_pizza_crust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='pizza',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pizza'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(choices=[('mozzarella', 'mozzarella')], default='mozzarella', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('normal', 'normal')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('medium', 'medium')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='main.pizzatopping'),
        ),
    ]
