# Generated by Django 5.1.6 on 2025-02-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delivery_pizza_alter_pizza_cheese_alter_pizza_crust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(choices=[('moz', 'moz')], default='mozzarella', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('thin', 'thin')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('large', 'large')], default='medium', max_length=20),
        ),
    ]
