# Generated by Django 5.1.6 on 2025-02-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_delivery_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(choices=[('Mozzarella', 'Mozzarella'), ('Vegan', 'Vegan'), ('Low Fat Mozzarella', 'Low Fat Mozzarella'), ('Cheddar', 'Cheddar'), ('Parmesan', 'Parmesan')], default='mozzarella', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('Thin', 'Thin'), ('Thick', 'Thick'), ('Stuffed', 'Stuffed'), ('Neapolitan', 'Neapolitan')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(choices=[('Tomato', 'Tomato'), ('Marinara', 'Marinara'), ('Alfredo', 'Alfredo'), ('BBQ', 'BBQ')], default='tomato', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], default='medium', max_length=20),
        ),
    ]
